### ISSUE TITLE
Range issue with blend micro...!

### ISSUE THREAD

**Issue by iqbalpalemad** [RedBearLab/nRF8001#14]
Hai

i am using blend micro to control my devices in my project via bluetooth.Now everything is working fine but the problem is with its range i have only getting a range of 13M but that is not enough for my project so can i increase the transmission power of my board to get more range ............?
or can i increase the range by any other means.......?

**Comment by XuGuohui** [comment]
Closed because it has been answered on RedBear forum:

 http://discuss.redbear.cc/t/how-to-add-extra-components-like-a-rgb-led-strip-an-lcd-tft-display-and-a-speaker-on-redbear-duo/1147/2
