### ISSUE TITLE
ble_set_name before ble_begin doesn't work.

### ISSUE THREAD

**Issue by FranticRain** [RedBearLab/nRF8001#9]
The README clearly states: "Before calling to ble_begin(), you can make use of ble_set_name("My BLE") to change the name." However, if you open up the simple chat example, uncomment the ble_set_name line, and then upload the program, the name will still be "BLE Shield" and not "My Name" as expected. I checked this using the Red Bear's Simple Chat iOS app.

I am using BLE Shield v2.0 on an Arduino Mega 2560 v3 using the latest version of the library. I am uploading to the board with an AVRISP MkII.

**Comment by Cheong2K** [comment]
Hi,
iOS will cache the name, I am not sure any method to refresh the name.
However, after changed the name, reconnect to the device again will see the change.

**Comment by FranticRain** [comment]
You are correct. Sorry about that.
